remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: "A Journey into the Core of Xavier Initialization"
description: >
  A Journey into the Core of Xavier Initialization from the math foundations.
  <br><br>
  <strong>Chapters:</strong><br>
  <a href="https://bastianru.github.io/xavier-init-from-scratch/es/Capitulo-0">📖 Capitulo 0 (ES)</a><br>
  <a href="https://bastianru.github.io/xavier-init-from-scratch/en/Chapter-0">📖 Chapter 0 (EN)</a>


markdown: kramdown
highlighter: rouge

